"""Pydantic models for PromptLab"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field
from uuid import uuid4


def generate_id() -> str:
    """Function to generate unique ID."""
    return str(uuid4())

def get_current_time() -> datetime:
    """Function to get current datetime."""
    return datetime.utcnow()


# ============== Prompt Models ==============
class PromptBase(BaseModel):
    """Base model for a prompt.

    Attributes:
        title (str): The title of the prompt, with a minimum length of 1 and a maximum of 200 characters.
        content (str): The main content of the prompt, with a minimum length of 1 character.
        description (Optional[str]): A brief description of the prompt, with a maximum of 500 characters.
        collection_id (Optional[str]): An optional identifier for the collection this prompt belongs to.

    Example:
        >>> prompt_base = PromptBase(
        ...     title="Example Title",
        ...     content="This is an example content.",
        ...     description="This is an example description.",
        ...     collection_id="123e4567-e89b-12d3-a456-426614174000"
        ... )
    """
    title: str = Field(..., min_length=1, max_length=200)
    content: str = Field(..., min_length=1)
    description: Optional[str] = Field(None, max_length=500)
    collection_id: Optional[str] = None


class PromptCreate(PromptBase):
    """Model for creating a new prompt, inheriting from PromptBase.

    Example:
        >>> new_prompt = PromptCreate(
        ...     title="New Prompt",
        ...     content="Content for the new prompt.",
        ...     description="Optional description for the new prompt."
        ... )
    """
    pass


class PromptUpdate(PromptBase):
    """Model for updating an existing prompt, inheriting from PromptBase.

    Example:
        >>> update_prompt = PromptUpdate(
        ...     title="Updated Title",
        ...     content="Updated content."
        ... )
    """
    pass

class PromptPatch(BaseModel):
    """Model for partially updating a prompt. All fields are optional.

    Attributes:
        title (Optional[str]): The title of the prompt, optional for partial updates.
        content (Optional[str]): The content of the prompt, optional for partial updates.
        description (Optional[str]): A description of the prompt, optional for partial updates.
        collection_id (Optional[str]): An optional identifier for the collection, optional for partial updates.

    Example:
        >>> patch_prompt = PromptPatch(
        ...     title="Partial Update Title"
        ... )
    """
    title: Optional[str] = Field(None, min_length=1, max_length=200)
    content: Optional[str] = Field(None, min_length=1)
    description: Optional[str] = Field(None, max_length=500)
    collection_id: Optional[str] = None


class Prompt(PromptBase):
    """Model representing a full prompt with metadata, inheriting from PromptBase.

    Attributes:
        id (str): Unique identifier for the prompt, generated by default.
        created_at (datetime): Timestamp when the prompt was created, generated by default.
        updated_at (datetime): Timestamp when the prompt was last updated, generated by default.

    Example:
        >>> prompt = Prompt(
        ...     title="Full Prompt",
        ...     content="Comprehensive content.",
        ...     id="507f1f77bcf86cd799439011"
        ... )
    """
    id: str = Field(default_factory=generate_id)
    created_at: datetime = Field(default_factory=get_current_time)
    updated_at: datetime = Field(default_factory=get_current_time)

    class Config:
        from_attributes = True


# ============== Collection Models ==============

class CollectionBase(BaseModel):
    """Base model for a collection.

    Attributes:
        name (str): The name of the collection, with a min length of 1 and max length of 100 characters.
        description (Optional[str]): A description of the collection, with a max length of 500 characters.

    Example:
        collection_base = CollectionBase(name="My Collection")
    """
    name: str = Field(..., min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=500)


class CollectionCreate(CollectionBase):
    """Model for creating an collection, inheriting from CollectionBase."""
    pass


class Collection(CollectionBase):
    """Model representing a complete collection entry.

    Attributes:
        id (str): Unique identifier for the collection, generated automatically.
        created_at (datetime): Time when the collection was created, generated automatically.

    Inherits from:
        CollectionBase

    Example:
        collection = Collection(id="123", name="Collection A")
    """
    id: str = Field(default_factory=generate_id)
    created_at: datetime = Field(default_factory=get_current_time)

    class Config:
        from_attributes = True


# ============== Response Models ==============

class PromptList(BaseModel):
    """Represents a list of prompts with a total count.

    Attributes:
        prompts (List[Prompt]): A list containing prompt objects.
        total (int): The total number of prompts in the list.

    Example:
        prompt_list = PromptList(prompts=[Prompt(...), ...], total=5)
    """
    prompts: List[Prompt]
    total: int


class CollectionList(BaseModel):
    """Represents a list of collections with a total count.

    Attributes:
        collections (List[Collection]): A list containing collection objects.
        total (int): The total number of collections in the list.

    Example:
        collection_list = CollectionList(collections=[Collection(...), ...], total=2)
    """
    collections: List[Collection]
    total: int


class HealthResponse(BaseModel):
    """Represents the health check response of the system.

    Attributes:
        status (str): The current status of the system, e.g., 'healthy'.
        version (str): The current version of the system.

    Example:
        health_response = HealthResponse(status='healthy', version='1.0.0')
    """
    status: str
    version: str
